### ISSUE TITLE
Support question

### ISSUE THREAD

**Issue by tresf** [swh/LRDF#10]
Hi!

I'm looking into the possibility of introducing RDF support into LMMS for populating the GUI with more human-readable values for the LADSPA plugins.

I have a few questions and was hoping to get some direction... (Warning, I don't know very much about LADSPA)

 * Assuming we stick with LADSPA for a while, is LRDF the best way to go?
 * Reading the [Ardour source code](https://github.com/Ardour/ardour/blob/master/libs/ardour/ladspa_plugin.cc#L748) I see a lot of "presets" type usage.  Is this for creating the RDFs?
 * When LADSPA plugins such as [TAP claim to support RDF](http://tap-plugins.sourceforge.net/ladspa.html) is that simply a way of stating they ship with RDF files or is there more happening under the scenes that we can make use of?
 * Is reading the LRDF source the best way to learn its usage?

Sorry if these are very novice questions.  Thanks for reading!

-Tres

**Comment by swh** [comment]
I'm not sure how widely RDF is supported in LADSPA plugins, I know mine had RDF files, and it sounds like TAP do, but how many more?

If you want to add support, then I'd guess LRDF is the best route, it's packaged by quite a few distros.

**Comment by tresf** [comment]
Thanks for chiming in.  Was really hoping for a quick enhancement, but after examining the effort, our efforts are probably better spent elsewhere.

Here's the cross-post for others that may be interested.  Closing both out for now, but feel free to chime in with comments. :beer: 
https://github.com/LMMS/lmms/issues/1717
