### ISSUE TITLE
is this the replacement to liblrdf?

### ISSUE THREAD

**Issue by shevegen** [swh/LRDF#14]
Hello Steve,

Could the main readme (or some other file) state whether LRDF is the replacement to the old liblrdf from sourceforge?

Reason I ask is that I collect recipes/cookbooks to install programs from source, and liblrdf has not been updated in about 14 years or so; whereas LRDF appears to be active. Hope I could explain the issue request here - please do feel free to close this issue here at any moment in time though. :)

**Comment by swh** [comment]
Done
